package p5;

import java.util.Random;

/**
 * SimpleDice creates a dice with a minimum of 1 side, if a lower value is entered by the user this exception
 * will be caught and will retunr a statement saying there can not be a dice with sides less than one.
 * @author JakeODonnell
 *
 */

public class SimpleDice implements Dice{
	
	private int sides; 
	public Random rand;
	
	/**
	 * Implements the interface Dice
	 * @author JakeODonnell
	 *
	 */
	public interface Dice { 
		public int throwDice();
		public int getSides();
	}
	
	/**
	 * Only used if the dice has 6 sides.
	 */
	
	public SimpleDice() {
		this(6);
	} 
	
	/**
	 * This constructor creates a dice with a random number of sides, however the dice must have atleast 1 side.
	 * @param sides
	 */
	
	public SimpleDice(int sides) {
		if(sides > 0) {
			this.sides = sides;
			this.rand = new Random(); 
		}
		else {
			throw new NegativeSidesException("Tärningen måste ha minst en sida");
		}
		
	} 
	
	/**
	 * This metod retruns the "sides" value generated by a random number that starts at +1. 
	 * @return sides
	 */
	
	public int throwDice() {
		return rand.nextInt(sides) + 1;
	}
	
	/**
	 * This metod returns the sides value
	 * @return sides
	 */
	
	public int getSides() {
		return sides;
	}
}
